from __future__ import annotations

import os
from pathlib import Path

from .constants import CARE_DIR
from .context import find_workflow_root, read_state
from .dashboard import render_dashboard
from .repo_status import render_repo_status

AGENT_DIR = ".agent"


def _rel(root: Path, path: Path) -> str:
    try:
        return path.relative_to(root).as_posix()
    except ValueError:
        return path.as_posix()


def _rel_from(base_dir: Path, path: Path) -> str:
    return Path(os.path.relpath(path, start=base_dir)).as_posix()


def _link(root: Path, path: Path, label: str | None = None, *, from_dir: Path | None = None) -> str:
    rel = _rel_from(from_dir, path) if from_dir else _rel(root, path)
    return f"[{label or _rel(root, path)}]({rel})"


def _active_paths(root: Path) -> dict[str, Path | str | None]:
    state = read_state(root)
    case_id = state.get("active_case") if isinstance(state.get("active_case"), str) else None
    order_id = state.get("active_order") if isinstance(state.get("active_order"), str) else None
    expected = state.get("expected_result_path") if isinstance(state.get("expected_result_path"), str) else None
    case_root = root / CARE_DIR / "cases" / case_id if case_id else None
    order_path = None
    if case_root and order_id:
        name = order_id if order_id.endswith(".order.md") else f"{order_id}.order.md"
        order_path = case_root / "orders" / name
    result_path = None
    if expected:
        candidate = Path(expected)
        result_path = candidate if candidate.is_absolute() else root / candidate
    elif case_root and order_id:
        result_path = case_root / "results" / f"{order_id}.result.md"
    return {
        "case_id": case_id,
        "order_id": order_id,
        "case_root": case_root,
        "case_path": case_root / "CASE.yaml" if case_root else None,
        "plan_path": case_root / "PLAN.md" if case_root else None,
        "order_path": order_path,
        "result_path": result_path,
        "dashboard_path": root / CARE_DIR / "INDEX.md",
    }


def _files(root: Path, case_root: Path | None, child: str) -> list[Path]:
    if not case_root:
        return []
    directory = case_root / child
    if not directory.exists():
        return []
    return sorted(path for path in directory.iterdir() if path.is_file())


def _bullet_links(root: Path, files: list[Path], empty: str, *, from_dir: Path | None = None) -> list[str]:
    if not files:
        return [f"- {empty}"]
    return [f"- {_link(root, path, from_dir=from_dir)}" for path in files]


def render_workspace_readme(cwd: Path) -> str:
    root = find_workflow_root(cwd)
    return "\n".join([
        "# Agent Workspace",
        "",
        "This directory is a human-facing workspace generated by `agent-careflow workspace --write`.",
        "",
        f"Canonical state remains in `{CARE_DIR}/`; `.agent/` is an index and resume surface, not the source of truth.",
        "",
        "## Start Here",
        "",
        "- [Current work](current.md)",
        "- [Canonical careflow index](../.careflow/INDEX.md)",
        "- [Incidents](incidents/README.md)",
        "- [Reviews](reviews/README.md)",
        "- [Learnings](learnings/README.md)",
        "- [Repositories](repos.md)",
        "",
        "## Rule",
        "",
        "Agents may read `.agent/` to orient themselves, but must write plans, orders, results, evidence, incidents, reviews, and learnings to `.careflow/` unless a specific ORDER says otherwise.",
        "",
    ])


def render_workspace_current(cwd: Path) -> str:
    root = find_workflow_root(cwd)
    paths = _active_paths(root)
    case_root = paths["case_root"] if isinstance(paths["case_root"], Path) else None
    current_dir = root / AGENT_DIR
    lines = [
        "# Current Agent Work",
        "",
        "workflow_root: `.`",
        f"active_case: `{paths['case_id'] or 'none'}`",
        f"active_order: `{paths['order_id'] or 'none'}`",
        "",
        "## Required Handoff Header",
        "",
        "```text",
        f"PLAN_FILE: {_rel(root, paths['plan_path']) if isinstance(paths['plan_path'], Path) else 'none'}",
        f"ORDER_FILE: {_rel(root, paths['order_path']) if isinstance(paths['order_path'], Path) else 'none'}",
        f"SUBPLAN_FILE: {_rel(root, paths['order_path']) if isinstance(paths['order_path'], Path) else 'none'}",
        f"EXPECTED_RESULT_PATH: {_rel(root, paths['result_path']) if isinstance(paths['result_path'], Path) else 'none'}",
        f"CASE_ID: {paths['case_id'] or 'none'}",
        f"ORDER_ID: {paths['order_id'] or 'none'}",
        "ASSIGNED_ROLE: <researcher|implementer|verifier|reviewer|incident-commander>",
        "TARGET_TOOL: <codex|claude|cursor>",
        "```",
        "",
        "## Links",
        "",
    ]
    for label, key in (("Careflow index", "dashboard_path"), ("Case", "case_path"), ("Plan", "plan_path"), ("Order", "order_path"), ("Expected result", "result_path")):
        path = paths[key]
        if isinstance(path, Path):
            lines.append(f"- {label}: {_link(root, path, from_dir=current_dir)}")
        else:
            lines.append(f"- {label}: `none`")
    lines.extend([
        "",
        "## Open Incidents",
        "",
        *_bullet_links(root, _files(root, case_root, "incidents"), "No incidents recorded.", from_dir=current_dir),
        "",
        "## Reviews",
        "",
        *_bullet_links(root, _files(root, case_root, "reviews"), "No reviews recorded.", from_dir=current_dir),
        "",
        "## Learnings",
        "",
        *_bullet_links(root, _files(root, case_root, "learnings"), "No learnings recorded.", from_dir=current_dir),
        "",
        "## Canonical Dashboard",
        "",
        "Open the canonical dashboard when you need the full case index: " + _link(root, paths["dashboard_path"], "careflow index", from_dir=current_dir) if isinstance(paths["dashboard_path"], Path) else "No dashboard path available.",
        "",
    ])
    return "\n".join(lines)


def render_workspace_listing(cwd: Path, child: str, title: str, empty: str) -> str:
    root = find_workflow_root(cwd)
    paths = _active_paths(root)
    case_root = paths["case_root"] if isinstance(paths["case_root"], Path) else None
    listing_dir = root / AGENT_DIR / child
    return "\n".join([
        f"# {title}",
        "",
        f"active_case: `{paths['case_id'] or 'none'}`",
        "",
        *_bullet_links(root, _files(root, case_root, child), empty, from_dir=listing_dir),
        "",
        "Canonical files live under `.careflow/`; this page is an operator index.",
        "",
    ])


def write_workspace(cwd: Path) -> list[Path]:
    root = find_workflow_root(cwd)
    workspace = root / AGENT_DIR
    files = {
        workspace / "README.md": render_workspace_readme(cwd),
        workspace / "current.md": render_workspace_current(cwd),
        workspace / "incidents" / "README.md": render_workspace_listing(cwd, "incidents", "Agent Incidents", "No incidents recorded."),
        workspace / "reviews" / "README.md": render_workspace_listing(cwd, "reviews", "Agent Reviews", "No reviews recorded."),
        workspace / "learnings" / "README.md": render_workspace_listing(cwd, "learnings", "Agent Learnings", "No learnings recorded."),
        workspace / "repos.md": render_repo_status(root),
    }
    written: list[Path] = []
    for path, text in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text.rstrip() + "\n", encoding="utf-8")
        written.append(path)
    return written
